### PR TITLE
allow run test without coverage

### PR DESCRIPTION
**Pull request by thuvh**

### CODE REVIEW

**Review by jamescurtin — CHANGES_REQUESTED** [review]
Thanks for submitting a PR! To preserve the current default behavior, what do you think about leaving the `default` kwarg unchanged, and instead add a `--no-coverage` option? ([see `click` docs](https://click.palletsprojects.com/en/8.1.x/options/#boolean-flags))

**Comment by thuvh** [comment]
I send output of command:

1. `flask test --coverage > test-no-coverage-long-code.txt 2>&1` [test-coverage-long-code.txt](https://github.com/cookiecutter-flask/cookiecutter-flask/files/11035876/test-coverage-long-code.txt)
2. `flask test --no-coverage > test-coverage-long-code.txt 2>&1` [test-no-coverage-long-code.txt](https://github.com/cookiecutter-flask/cookiecutter-flask/files/11035878/test-no-coverage-long-code.txt)
3. `flask test -c > test-coverage-short-code.txt 2>&1`  [test-coverage-short-code.txt](https://github.com/cookiecutter-flask/cookiecutter-flask/files/11035877/test-coverage-short-code.txt)
4. `flask test -C > test-no-coverage-short-code.txt 2>&1` [test-no-coverage-short-code.txt](https://github.com/cookiecutter-flask/cookiecutter-flask/files/11035879/test-no-coverage-short-code.txt)

I use *-c / -C* like *-l / -L* in [createuser](https://www.postgresql.org/docs/current/app-createuser.html)

**Review by jamescurtin — APPROVED** [review]
LGTM--thank you!

**Comment by jamescurtin** [comment]
> I send output of command:
> 
> 1. `flask test --coverage > test-no-coverage-long-code.txt 2>&1` [test-coverage-long-code.txt](https://github.com/cookiecutter-flask/cookiecutter-flask/files/11035876/test-coverage-long-code.txt)

I think the linked file might accidentally have the output from the `--no-coverage` version, but this is 👍

**Pull request merged**
