### PR TITLE
Fix missing environmental variables in travis.yml

### PR DESCRIPTION
**Pull request by TobKed**
I've add `DATABASE_URL` and `SECRET_KEY` because I received errors on Travis (due to missing environmental variables in `settings.py`)

### CODE REVIEW

**Comment by jamescurtin** [comment]
Thanks for the PR! 

All necessary environment variables are listed in `.env.example` along with defaults that are reasonable for testing. Rather than setting environment variables individually in the Travis config file, could we instead add an additional `before_script` step where `.env.example` is copied to `.env`?

I would prefer this approach, as it minimizes the number of places where config values are defined, and is more scalable, assuming we need to add additional config variables in the future.

**Comment by TobKed** [comment]
Thanks for a great suggestion @jamescurtin ! 
I've applied your idea about coping `.env.example` which cause that setting-up any environmental variables in `.travis.yml` is not required at all. What do you think about it now?

**Comment by jamescurtin** [comment]
Looks great! Have you tested this out on your generated project (this isn't something that we can directly test) 

With that confirmation, I'm happy to merge. Thanks for all of your contributions!

**Comment by TobKed** [comment]
I've tested it and it looks good, however there are 20 warnings caused by SQL-Alchemy:

> SADeprecationWarning: The Binary class is deprecated and will be removed in a future relase.  Please use LargeBinary.

Here is link for my test [travis build](https://travis-ci.org/TobKed/W-App/builds/586555859).

 The deprecated `Binary` class is used in `User` model. I've run tests with `LargeBinary` instead of `Binary` class used and there was no warning however I will investigate is it the best solution for this issue and and create separate PR. 
Source code of the warning: https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L986.
Source code of the `User` model with deprecated class: https://github.com/cookiecutter-flask/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/user/models.py#L42

**Pull request merged**
